# Generated by Django 5.1.7 on 2025-03-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fname_register_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='cateringservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('catering_package', models.CharField(choices=[('Simple', 'Simple (6-8 items)'), ('Standerd', 'Standard (10-12 items)'), ('Premium', 'Premium (15-20 items)')], max_length=20)),
                ('catering_type', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=10)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
