# Generated by Django 5.1.7 on 2025-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cateringservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
