# Generated by Django 5.1.7 on 2025-03-16 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('plans', models.CharField(max_length=50)),
                ('location', models.TextField(null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('features', models.TextField(null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_month', models.CharField(default='March', editable=False, max_length=10)),
                ('order_year', models.IntegerField(default=2025, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
            ],
        ),
    ]
