# Generated by Django 5.1.7 on 2025-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_reviews_alter_cateringservice_catering_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_month',
            field=models.CharField(default='April', editable=False, max_length=10),
        ),
    ]
